<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1

Subsetting - It means to select the elements that we want.  
Indexing - It means to select single elements.   
Slicing - It means to select a range of elements.   
Masking - It means to select and show the elements that fulfilled the criteria.  

## Exercise 2

In [16]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_2d_numbers_only = np.array(np_array_2d[:,0])
np_array_int = np_array_2d_numbers_only.astype(int)
np_array_remainder = np_array_int % 2
mask = np_array_remainder == 1
print(np_array_2d[mask][:,1])

['A' 'C' 'E' 'G' 'I']


## Exercise 3

In [21]:
numbers = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

mask = numbers < 50 
mask_1 = numbers > 50
mask_2 = numbers == 50

numbers[mask] = -1
numbers[mask_1] = 1
numbers[mask_2] = 0

print(numbers)
 

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
